name: Terraform Checks

on: [push]

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    container: smartrent/terraform-ci:1.0.11
    steps:
      - name: Clone Local Repo
        uses: actions/checkout@v2
        with:
            path: infrastructure/terraform/

      - name: Terraform init
        run: |
          terraform init -input=false
      
      - name: Verify Terraform version
        run: |
          terraform --version
      
      - name: terraform format
        run: |
          terraform fmt -check -recursive
      
      - name: tflint
        run: |
          tflint
     
      - name: Terraform validation
        run: |
          terraform validate