name: Deploy Infrastructure

on:
  push

defaults:
 run:
  working-directory: infrastructure/terraform/bot

jobs:
  deploy:
    name: Deploy Bot
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    - id: Terraform Init
    - run: terraform init

    - id: plan
      run: terraform plan -no-color

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}


    - id: Terraform Apply
      run: terraform apply -auto-approve
