name: Terraform
on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    container: smartrent/terraform-ci:1.0.11
    steps:
      - name: Clone Local Repo
        uses: actions/checkout@v2
        with:
            path: infrastructure/terraform/bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform init
        run: |
          terraform init -input=false
      
      - name: Verify Terraform version
        run: |
          terraform --version
      
      - name: terraform format
        run: |
          terraform fmt -check -recursive
      
      - name: tflint
        run: |
          tflint
     
      - name: Terraform validation
        run: |
          terraform validate
      
      - name: Terraform plan
        with: 
          path: infrastructure/terraform/bot
        run: |
          terraform plan -input=false -out=tfplan